server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://t3lfk4cjw00oku9n:gxu1zlntcyes87pg@bv2rebwf6zzsv341.cbetxkdyhwsb.us-east-1.rds.amazonaws.com/h510vhrwpiei2pzk?useUnicode=true&serverTimezone=Asia/Seoul
    username: t3lfk4cjw00oku9n
    password: gxu1zlntcyes87pg
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect : org.hibernate.dialect.MySQL8Dialect
    profiles:
      active: local
  logging:
    output:
      ansi:
        enabled: always
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.sql.BasicBinder: TRACE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012