export enum Department {
  사업 = 1,
  영업 = 2,
  개발 = 3,
  디자인 = 4,
  기획 = 5,
  관리 = 6,
  서비스 = 7,
}

export enum Category {
  '경제/경영' = 'ECONOMICS_MANAGEMENT',
  '자기계발' = 'SELF_IMPROVEMENT',
  '정치/사회' = 'POLITICS_SOCIETY',
  '컴퓨터/IT' = 'COMPUTER_IT',
  '취업/수험서' = 'EMPLOYMENT_EXAMS',
  '기술/공학' = 'TECHNOLOGY_ENGINEERING',
  '잡지' = 'MAGINE',
  '시/에세이' = 'POETRY_ESSAY',
  '인문' = 'HUMANITIES',
  '역사/문화' = 'HISTORY_CULTURE',
  '가정/육아' = 'FAMILY_PARENTING',
  '건강' = 'HEALTH',
  '예술/대중문화' = 'ART_POP_CULTURE',
  '여행' = 'TRAVEL',
  '외국어' = 'FOREIGN_LANGUAGE',
  '과학' = 'SCIENCE',
  '어린이(초등)' = 'CHILDREN_PRIMARY',
  '취미/실용/스포츠' = 'HOBBY_PRACTICAL_SPORTS',
  '소설' = 'NOVEL',
  '청소년' = 'TEENAGER',
  '만화' = 'COMICS',
  '서양도서' = '',
  '예술/건축' = 'ART_ARCHITECTURE',
  'IT/프로그래밍' = 'IT_PROGRAMMING',
}
